### ISSUE TITLE
Issue in df2md

### ISSUE THREAD

**Issue by BraINstinct0** [jehyunlee/code-snippet#1]
[df2md](https://github.com/jehyunlee/code-snippet/blob/master/3_pandas/df2md/df2md.md) uses '|' as separator when creating a markdown from a pandas DataFrame.
This mostly works well, but when the dataframe has a string including '|' , it doesn't work as intended.

**Comment by jehyunlee** [comment]
The '|' issue seems to be inevitable due to the definition of markdown cell syntax.
One candidate of the solution would be replacing '|' (unicode 007C) with '¦ ' (00A6) or similar foreign charactors in [unicode list](https://www.unicode.org/charts/nameslist/).
In spite of the serious data manipulation for the case the converted markdown table is used as another input, it would be possible to be applied with sacrifice of running time.
What do you think about that?

**Comment by jehyunlee** [comment]
I encountered similar situations that when dataset contains `markdown` characters such as *, ~, **, the data shown on table is **distorted**. Fortunately it's a rare case, but should be commented on top of the list to aware the users. 
Consequently, the function `df2md` should be used only for **visualize**, not as another input.

I'll close this issue.
